using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EfCoreLab.Data
{
    /// <summary>
    /// Bonus Challenge TelephoneNumber entity with advanced features:
    /// - IValidatableObject for custom validation
    /// - Auditing fields (CreatedDate, ModifiedDate)
    /// - Soft delete support (IsDeleted)
    /// </summary>
    public class BonusTelephoneNumber : IValidatableObject
    {
        /// <summary>
        /// Unique identifier for the phone number. Auto-generated by the database.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

        /// <summary>
        /// Foreign key reference to the Customer who owns this phone number.
        /// </summary>
        [Range(1, long.MaxValue, ErrorMessage = "CustomerId must be greater than zero.")]
        public long CustomerId { get; set; }

        /// <summary>
        /// The type of phone number. Must be one of: Mobile, Work, or DirectDial.
        /// </summary>
        [Required(ErrorMessage = "Type is required")]
        [RegularExpression("^(Mobile|Work|DirectDial)$", ErrorMessage = "Type must be Mobile, Work, or DirectDial.")]
        public string? Type { get; set; }

        /// <summary>
        /// The phone number string in any format.
        /// </summary>
        [Required(ErrorMessage = "Number is required")]
        [StringLength(50)]
        public string? Number { get; set; }

        // Auditing fields
        /// <summary>
        /// Date and time when the phone number record was created.
        /// Automatically set by EF Core interceptor.
        /// </summary>
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// Date and time when the phone number record was last modified.
        /// Automatically updated by EF Core interceptor.
        /// </summary>
        public DateTime ModifiedDate { get; set; }

        // Soft delete
        /// <summary>
        /// Indicates whether this phone number has been soft deleted.
        /// When true, the record is hidden from normal queries via global query filter.
        /// </summary>
        public bool IsDeleted { get; set; }

        /// <summary>
        /// Date and time when the phone number was soft deleted.
        /// Null if the phone number has not been deleted.
        /// </summary>
        public DateTime? DeletedDate { get; set; }

        /// <summary>
        /// Custom validation logic implementing IValidatableObject.
        /// </summary>
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            // Validation 1: Mobile numbers should contain digits
            if (!string.IsNullOrEmpty(Type) && Type == "Mobile" && !string.IsNullOrEmpty(Number))
            {
                if (!Number.Any(char.IsDigit))
                {
                    yield return new ValidationResult(
                        "Mobile phone number must contain at least one digit",
                        new[] { nameof(Number) });
                }
            }

            // Validation 2: Phone number should have minimum length
            if (!string.IsNullOrEmpty(Number) && Number.Replace(" ", "").Replace("-", "").Replace("+", "").Length < 8)
            {
                yield return new ValidationResult(
                    "Phone number must contain at least 8 digits",
                    new[] { nameof(Number) });
            }

            // Validation 3: Ensure deleted records have a DeletedDate
            if (IsDeleted && !DeletedDate.HasValue)
            {
                yield return new ValidationResult(
                    "DeletedDate must be set when IsDeleted is true",
                    new[] { nameof(DeletedDate) });
            }

            // Validation 4: CreatedDate should not be in the future
            if (CreatedDate > DateTime.UtcNow)
            {
                yield return new ValidationResult(
                    "CreatedDate cannot be in the future",
                    new[] { nameof(CreatedDate) });
            }

            // Validation 5: ModifiedDate should not be before CreatedDate
            if (ModifiedDate < CreatedDate)
            {
                yield return new ValidationResult(
                    "ModifiedDate cannot be before CreatedDate",
                    new[] { nameof(ModifiedDate) });
            }
        }
    }
}
