using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EfCoreLab.Data
{
    /// <summary>
    /// Bonus Challenge Invoice entity with advanced features:
    /// - IValidatableObject for custom validation
    /// - Auditing fields (CreatedDate, ModifiedDate)
    /// - Soft delete support (IsDeleted)
    /// </summary>
    public class BonusInvoice : IValidatableObject
    {
        /// <summary>
        /// Unique identifier for the invoice. Auto-generated by the database.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

        /// <summary>
        /// User-provided invoice number. Must start with "INV" and be unique across all customers.
        /// Example: "INV-12345678"
        /// </summary>
        [Required(ErrorMessage = "InvoiceNumber is required.")]
        [RegularExpression(@"^INV.*", ErrorMessage = "InvoiceNumber must start with 'INV'.")]
        [StringLength(50)]
        public string InvoiceNumber { get; set; } = string.Empty;

        /// <summary>
        /// Foreign key reference to the Customer who owns this invoice.
        /// </summary>
        [Range(1, long.MaxValue, ErrorMessage = "CustomerId must be greater than zero.")]
        public long CustomerId { get; set; }

        /// <summary>
        /// The date the invoice was issued.
        /// </summary>
        [Required]
        public DateTime InvoiceDate { get; set; }

        /// <summary>
        /// The monetary amount of the invoice.
        /// </summary>
        [Required]
        [Range(0.01, 1000000, ErrorMessage = "Amount must be between 0.01 and 1,000,000")]
        [Column(TypeName = "decimal(18,2)")]
        public decimal Amount { get; set; }

        // Auditing fields
        /// <summary>
        /// Date and time when the invoice record was created.
        /// Automatically set by EF Core interceptor.
        /// </summary>
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// Date and time when the invoice record was last modified.
        /// Automatically updated by EF Core interceptor.
        /// </summary>
        public DateTime ModifiedDate { get; set; }

        // Soft delete
        /// <summary>
        /// Indicates whether this invoice has been soft deleted.
        /// When true, the record is hidden from normal queries via global query filter.
        /// </summary>
        public bool IsDeleted { get; set; }

        /// <summary>
        /// Date and time when the invoice was soft deleted.
        /// Null if the invoice has not been deleted.
        /// </summary>
        public DateTime? DeletedDate { get; set; }

        /// <summary>
        /// Custom validation logic implementing IValidatableObject.
        /// </summary>
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            // Validation 1: InvoiceDate should not be in the future
            if (InvoiceDate > DateTime.UtcNow)
            {
                yield return new ValidationResult(
                    "Invoice date cannot be in the future",
                    new[] { nameof(InvoiceDate) });
            }

            // Validation 2: InvoiceDate should not be too old (e.g., more than 10 years)
            if (InvoiceDate < DateTime.UtcNow.AddYears(-10))
            {
                yield return new ValidationResult(
                    "Invoice date cannot be more than 10 years in the past",
                    new[] { nameof(InvoiceDate) });
            }

            // Validation 3: Ensure deleted records have a DeletedDate
            if (IsDeleted && !DeletedDate.HasValue)
            {
                yield return new ValidationResult(
                    "DeletedDate must be set when IsDeleted is true",
                    new[] { nameof(DeletedDate) });
            }

            // Validation 4: CreatedDate should not be in the future
            if (CreatedDate > DateTime.UtcNow)
            {
                yield return new ValidationResult(
                    "CreatedDate cannot be in the future",
                    new[] { nameof(CreatedDate) });
            }

            // Validation 5: ModifiedDate should not be before CreatedDate
            if (ModifiedDate < CreatedDate)
            {
                yield return new ValidationResult(
                    "ModifiedDate cannot be before CreatedDate",
                    new[] { nameof(ModifiedDate) });
            }

            // Validation 6: Amount should be positive
            if (Amount <= 0)
            {
                yield return new ValidationResult(
                    "Amount must be greater than zero",
                    new[] { nameof(Amount) });
            }
        }
    }
}
