using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EfCoreLab.Data
{
    /// <summary>
    /// Bonus Challenge Customer entity with advanced features:
    /// - IValidatableObject for custom validation
    /// - Auditing fields (CreatedDate, ModifiedDate)
    /// - Soft delete support (IsDeleted)
    /// </summary>
    public class BonusCustomer : IValidatableObject
    {
        /// <summary>
        /// Unique identifier for the customer. Auto-generated by the database.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

        /// <summary>
        /// Customer's name (typically a company name).
        /// </summary>
        [Required(ErrorMessage = "Name is required")]
        [StringLength(200, MinimumLength = 2, ErrorMessage = "Name must be between 2 and 200 characters")]
        public string? Name { get; set; }

        /// <summary>
        /// Customer's email address.
        /// </summary>
        [Required(ErrorMessage = "Email is required")]
        [EmailAddress(ErrorMessage = "Invalid email format")]
        [StringLength(200)]
        public string? Email { get; set; }

        /// <summary>
        /// Collection of invoices associated with this customer.
        /// </summary>
        public List<BonusInvoice>? Invoices { get; set; } = new List<BonusInvoice>();

        /// <summary>
        /// Collection of phone numbers associated with this customer.
        /// </summary>
        public List<BonusTelephoneNumber>? PhoneNumbers { get; set; } = new List<BonusTelephoneNumber>();

        /// <summary>
        /// Calculated property that returns the sum of all invoice amounts for this customer.
        /// Returns 0 if there are no invoices.
        /// </summary>
        [NotMapped]
        public decimal Balance => Invoices?.Sum(i => i.Amount) ?? 0;

        // Auditing fields
        /// <summary>
        /// Date and time when the customer record was created.
        /// Automatically set by EF Core interceptor.
        /// </summary>
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// Date and time when the customer record was last modified.
        /// Automatically updated by EF Core interceptor.
        /// </summary>
        public DateTime ModifiedDate { get; set; }

        // Soft delete
        /// <summary>
        /// Indicates whether this customer has been soft deleted.
        /// When true, the record is hidden from normal queries via global query filter.
        /// </summary>
        public bool IsDeleted { get; set; }

        /// <summary>
        /// Date and time when the customer was soft deleted.
        /// Null if the customer has not been deleted.
        /// </summary>
        public DateTime? DeletedDate { get; set; }

        /// <summary>
        /// Custom validation logic implementing IValidatableObject.
        /// Validates that the email domain matches the company name conventions.
        /// </summary>
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            // Validation 1: Email domain should somewhat relate to company name
            if (!string.IsNullOrEmpty(Email) && !string.IsNullOrEmpty(Name))
            {
                var emailDomain = Email.Split('@').LastOrDefault()?.ToLower();
                var nameParts = Name.ToLower().Split(' ');

                // Check if any part of the company name appears in the email domain
                bool hasMatchingDomain = nameParts.Any(part =>
                    part.Length > 3 && emailDomain?.Contains(part.Replace(" ", "")) == true);

                if (!hasMatchingDomain && !Email.Contains("example.com") && !Email.Contains("test.com"))
                {
                    yield return new ValidationResult(
                        "Email domain should relate to the company name for authenticity",
                        new[] { nameof(Email) });
                }
            }

            // Validation 2: Ensure deleted records have a DeletedDate
            if (IsDeleted && !DeletedDate.HasValue)
            {
                yield return new ValidationResult(
                    "DeletedDate must be set when IsDeleted is true",
                    new[] { nameof(DeletedDate) });
            }

            // Validation 3: Ensure non-deleted records don't have a DeletedDate
            if (!IsDeleted && DeletedDate.HasValue)
            {
                yield return new ValidationResult(
                    "DeletedDate should be null when IsDeleted is false",
                    new[] { nameof(DeletedDate) });
            }

            // Validation 4: CreatedDate should not be in the future
            if (CreatedDate > DateTime.UtcNow)
            {
                yield return new ValidationResult(
                    "CreatedDate cannot be in the future",
                    new[] { nameof(CreatedDate) });
            }

            // Validation 5: ModifiedDate should not be before CreatedDate
            if (ModifiedDate < CreatedDate)
            {
                yield return new ValidationResult(
                    "ModifiedDate cannot be before CreatedDate",
                    new[] { nameof(ModifiedDate) });
            }
        }
    }
}
